#! /bin/bash
# Transfers CA certificates imported in initramfs via kickstart
# to anaconda environment after switchroot.

# certificates dumped to the specified file are copied to root
cp -rv /run/install/certificates/path/* /

# 'global' category certificates are iported to root global store
trust anchor /run/install/certificates/category/global/*
