name: Run kickstart smoke tests
on: pull_request

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  kickstar-smoke-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Find the checks
        uses: octokit/request-action@v2.x
        id: list_check_runs
        with:
          route: GET /repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs
          check_name: "kickstar-smoke-test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show the checks
        run:
          echo "${{ steps.list_check_runs.outputs.data }}"
          echo "${{ fromJson(steps.list_check_runs.outputs.data).check_runs[0].id }}"

      - name: Update status of kickstart-test check as pending and set info about how to run it
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/check-runs/${{ fromJson(steps.list_check_runs.outputs.data).check_runs[0].id }}
          status: 'queued'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set result status
        if: always()
        uses: octokit/request-action@v2.x
        with:
          route: 'POST /repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}'
          context: "Run kickstart smoke tests"
          state: 'pending'
          #target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


