name: Run validation tests
on: pull_request_target

jobs:
  unit-tests:
    environment: staging
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # * Don't forget to copypaste also the same matrix below in rpm tests!
        # * Replace current branch in "release" with empty string. This makes name of the check for
        #   the current branch always have the same name, so that it can be added to required
        #   checks.
        # * For various branches, comment out what does not apply:
        #     on -devel, run everything
        #     on -release, only -release
        #     on master, only master and ELN
        #release: [master, eln, '', f34-release]
        release: ['']
        include:
          - release: ''
            target_branch: 'master'
            ci_tag: 'master'
          #- release: eln
          #  target_branch: 'master'
          #  ci_tag: 'eln'
          #  build-args: '--build-arg=image=quay.io/fedoraci/fedora:eln-x86_64'
          #- release: f34-devel
          #  target_branch: 'f34-devel'
          #  ci_tag: 'f34-devel'
          #- release: f34-release
          #  target_branch: 'f34-release'
          #  ci_tag: 'f34-release'
    env:
      CI_TAG: '${{ matrix.ci_tag }}'
      CONTAINER_BUILD_ARGS: '${{ matrix.build-args }}'
      TARGET_BRANCH_NAME: 'origin/${{ matrix.target_branch }}'

    steps:
      # FIXME: This is a temporary workaround for Ubuntu 20.04 20210419.1.
      # See: https://github.com/actions/virtual-environments/issues/3229
      - name: Fix the broken rootless podman on Ubuntu 20.04 20210419.1
        run: |
          # Create directories for a custom storage configuration file.
          mkdir -p ~/.config/containers/

          # Create a custom storage configuration file for the rootless mode.
          cat > ~/.config/containers/storage.conf << EOF

          [storage]
          driver = "overlay"
          graphroot = "/home/runner/.local/share/containers/storage"

          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
          additionalimagestores = []

          EOF

      - name: Clone repository
        uses: actions/checkout@v2.3.4
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Rebase to current ${{ env.TARGET_BRANCH_NAME }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git log --oneline -1 ${{ env.TARGET_BRANCH_NAME }}
          git rebase ${{ env.TARGET_BRANCH_NAME }}

      - name: Check if rebuild of the container image is required
        id: check-dockerfile-changed
        run: |
          changes=$(git diff $TARGET_BRANCH_NAME..HEAD -- dockerfile/anaconda-ci/ anaconda.spec.in scripts/testing/install_dependencies.sh)
          # print for debugging
          echo "$changes"
          [ -z "$changes" ] || echo "::set-output name=changed::true"

      # build container if files for dockerfile changed in the PR
      - name: Build anaconda-ci container
        # FIXME: always build ELN container, until we publish it to quay.io
        if: steps.check-dockerfile-changed.outputs.changed || matrix.release == 'eln'
        run: make -f Makefile.am anaconda-ci-build

      - name: Run tests in anaconda-ci container
        run: |
          # put the log in the output, where it's easy to read and link to
          make -f Makefile.am container-ci || { cat test-logs/test-suite.log; exit 1; }

      - name: Upload test and coverage logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'logs (${{ matrix.ci_tag }})'
          path: test-logs/*

  rpm-tests:
    environment: staging
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # For matrix details, see comments for the unit tests above.
        #release: [master, eln, '', f34-release]
        release: ['']
        include:
          - release: ''
            target_branch: 'master'
            ci_tag: 'master'
          #- release: eln
          #  target_branch: 'master'
          #  ci_tag: 'eln'
          #  build-args: '--build-arg=image=quay.io/fedoraci/fedora:eln-x86_64'
          #- release: f34-devel
          #  target_branch: 'f34-devel'
          #  ci_tag: 'f34-devel'
          #- release: f34-release
          #  target_branch: 'f34-release'
          #  ci_tag: 'f34-release'
    env:
      CI_TAG: '${{ matrix.ci_tag }}'
      CONTAINER_BUILD_ARGS: '${{ matrix.build-args }}'
      TARGET_BRANCH_NAME: 'origin/${{ matrix.target_branch }}'

    steps:
      # FIXME: This is a temporary workaround for Ubuntu 20.04 20210419.1.
      # See: https://github.com/actions/virtual-environments/issues/3229
      - name: Fix the broken rootless podman on Ubuntu 20.04 20210419.1
        run: |
          # Create directories for a custom storage configuration file.
          mkdir -p ~/.config/containers/

          # Create a custom storage configuration file for the rootless mode.
          cat > ~/.config/containers/storage.conf << EOF

          [storage]
          driver = "overlay"
          graphroot = "/home/runner/.local/share/containers/storage"

          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
          additionalimagestores = []

          EOF

      - name: Clone repository
        uses: actions/checkout@v2.3.4
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Rebase to current ${{ env.TARGET_BRANCH_NAME }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git log --oneline -1 ${{ env.TARGET_BRANCH_NAME }}
          git rebase ${{ env.TARGET_BRANCH_NAME }}

      - name: Build RPM test container
        run: make -f Makefile.am anaconda-rpm-build

      - name: Run RPM tests in container
        run: make -f Makefile.am container-rpm-test

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'logs-rpm-test (${{ matrix.ci_tag }})'
          path: test-logs/*
